from core.restclient.v2_0.agilitymodel.base.AgilityModelBase import AgilityModelBase
from core.restclient.v2_0.agilitymodel.base.EULA import EULABase
from core.restclient.v2_0.agilitymodel.base.NetworkServiceType import NetworkServiceTypeBase
from core.restclient.v2_0.agilitymodel.base.PropertyDefinition import PropertyDefinitionBase
from core.restclient.v2_0.agilitymodel.base.StorePrice import StorePriceBase
from core.restclient.v2_0.agilitymodel.base.ConfigurationPolicyMeta import ConfigurationPolicyMetaBase
from core.restclient.v2_0.agilitymodel.base.IntegerRangeValidator import IntegerRangeValidatorBase
from core.restclient.v2_0.agilitymodel.base.AccessList import AccessListBase
from core.restclient.v2_0.agilitymodel.base.Authentication import AuthenticationBase
from core.restclient.v2_0.agilitymodel.base.Asset import AssetBase
from core.restclient.v2_0.agilitymodel.base.Template import TemplateBase
from core.restclient.v2_0.agilitymodel.base.ConfigProperty import ConfigPropertyBase
from core.restclient.v2_0.agilitymodel.base.IntegerScaleValidator import IntegerScaleValidatorBase
from core.restclient.v2_0.agilitymodel.base.ResourceWeightInfo import ResourceWeightInfoBase
from core.restclient.v2_0.agilitymodel.base.Credential import CredentialBase
from core.restclient.v2_0.agilitymodel.base.EffectiveProtocolRequest import EffectiveProtocolRequestBase
from core.restclient.v2_0.agilitymodel.base.ResourceMetrics import ResourceMetricsBase
from core.restclient.v2_0.agilitymodel.base.BlueprintRef import BlueprintRefBase
from core.restclient.v2_0.agilitymodel.base.IntegerRange import IntegerRangeBase
from core.restclient.v2_0.agilitymodel.base.Host import HostBase
from core.restclient.v2_0.agilitymodel.base.AddressList import AddressListBase
from core.restclient.v2_0.agilitymodel.base.VersionList import VersionListBase
from core.restclient.v2_0.agilitymodel.base.StoreProductType import StoreProductTypeBase
from core.restclient.v2_0.agilitymodel.base.ResourcePolicy import ResourcePolicyBase
from core.restclient.v2_0.agilitymodel.base.WorkflowTaskMeta import WorkflowTaskMetaBase
from core.restclient.v2_0.agilitymodel.base.CloudMetaModel import CloudMetaModelBase
from core.restclient.v2_0.agilitymodel.base.AccessRightSet import AccessRightSetBase
from core.restclient.v2_0.agilitymodel.base.Task import TaskBase
from core.restclient.v2_0.agilitymodel.base.ConfigSettings import ConfigSettingsBase
from core.restclient.v2_0.agilitymodel.base.Address import AddressBase
from core.restclient.v2_0.agilitymodel.base.CustomItem import CustomItemBase
from core.restclient.v2_0.agilitymodel.base.Project import ProjectBase
from core.restclient.v2_0.agilitymodel.base.NameValuePair import NameValuePairBase
from core.restclient.v2_0.agilitymodel.base.StoreProductAdapterItemList import StoreProductAdapterItemListBase
from core.restclient.v2_0.agilitymodel.base.OnboardMeta import OnboardMetaBase
from core.restclient.v2_0.agilitymodel.base.EnvironmentType import EnvironmentTypeBase
from core.restclient.v2_0.agilitymodel.base.PriceEngine import PriceEngineBase
from core.restclient.v2_0.agilitymodel.base.ImportDirectives import ImportDirectivesBase
from core.restclient.v2_0.agilitymodel.base.VersionedItemLink import VersionedItemLinkBase
from core.restclient.v2_0.agilitymodel.base.Protocol import ProtocolBase
from core.restclient.v2_0.agilitymodel.base.Taxonomy import TaxonomyBase
from core.restclient.v2_0.agilitymodel.base.DeploymentArtifactConfig import DeploymentArtifactConfigBase
from core.restclient.v2_0.agilitymodel.base.PublishRequest import PublishRequestBase
from core.restclient.v2_0.agilitymodel.base.ServiceBindingType import ServiceBindingTypeBase
from core.restclient.v2_0.agilitymodel.base.DesignItem import DesignItemBase
from core.restclient.v2_0.agilitymodel.base.TargetCloud import TargetCloudBase
from core.restclient.v2_0.agilitymodel.base.AssetProperty import AssetPropertyBase
from core.restclient.v2_0.agilitymodel.base.LifecyclePolicyMeta import LifecyclePolicyMetaBase
from core.restclient.v2_0.agilitymodel.base.AssetTypeBrief import AssetTypeBriefBase
from core.restclient.v2_0.agilitymodel.base.ResourceMatch import ResourceMatchBase
from core.restclient.v2_0.agilitymodel.base.StorageSnapshot import StorageSnapshotBase
from core.restclient.v2_0.agilitymodel.base.LdapGroupList import LdapGroupListBase
from core.restclient.v2_0.agilitymodel.base.StoreResource import StoreResourceBase
from core.restclient.v2_0.agilitymodel.base.Script import ScriptBase
from core.restclient.v2_0.agilitymodel.base.NetworkInterfaceList import NetworkInterfaceListBase
from core.restclient.v2_0.agilitymodel.base.Storage import StorageBase
from core.restclient.v2_0.agilitymodel.base.AssetTypeMeta import AssetTypeMetaBase
from core.restclient.v2_0.agilitymodel.base.Location import LocationBase
from core.restclient.v2_0.agilitymodel.base.ArtifactAttachment import ArtifactAttachmentBase
from core.restclient.v2_0.agilitymodel.base.PropertyMatch import PropertyMatchBase
from core.restclient.v2_0.agilitymodel.base.Parameter import ParameterBase
from core.restclient.v2_0.agilitymodel.base.AssetTypeList import AssetTypeListBase
from core.restclient.v2_0.agilitymodel.base.Deployer import DeployerBase
from core.restclient.v2_0.agilitymodel.base.InputVariableList import InputVariableListBase
from core.restclient.v2_0.agilitymodel.base.StoreProductAdapter import StoreProductAdapterBase
from core.restclient.v2_0.agilitymodel.base.Link import LinkBase
from core.restclient.v2_0.agilitymodel.base.StoreReleaseType import StoreReleaseTypeBase
from core.restclient.v2_0.agilitymodel.base.FileSystem import FileSystemBase
from core.restclient.v2_0.agilitymodel.base.ResourceWeightMetaList import ResourceWeightMetaListBase
from core.restclient.v2_0.agilitymodel.base.DeploymentConfiguration import DeploymentConfigurationBase
from core.restclient.v2_0.agilitymodel.base.PermissionType import PermissionTypeBase
from core.restclient.v2_0.agilitymodel.base.StoreProduct import StoreProductBase
from core.restclient.v2_0.agilitymodel.base.AliasList import AliasListBase
from core.restclient.v2_0.agilitymodel.base.AssetType import AssetTypeBase
from core.restclient.v2_0.agilitymodel.base.Workload import WorkloadBase
from core.restclient.v2_0.agilitymodel.base.AccessUri import AccessUriBase
from core.restclient.v2_0.agilitymodel.base.StoreEditionType import StoreEditionTypeBase
from core.restclient.v2_0.agilitymodel.base.LdapGroup import LdapGroupBase
from core.restclient.v2_0.agilitymodel.base.AddressRange import AddressRangeBase
from core.restclient.v2_0.agilitymodel.base.VariableValueSet import VariableValueSetBase
from core.restclient.v2_0.agilitymodel.base.Linklist import LinklistBase
from core.restclient.v2_0.agilitymodel.base.Command import CommandBase
from core.restclient.v2_0.agilitymodel.base.UserGroup import UserGroupBase
from core.restclient.v2_0.agilitymodel.base.ItemLink import ItemLinkBase
from core.restclient.v2_0.agilitymodel.base.Property import PropertyBase
from core.restclient.v2_0.agilitymodel.base.Comment import CommentBase
from core.restclient.v2_0.agilitymodel.base.Domain import DomainBase
from core.restclient.v2_0.agilitymodel.base.Repository import RepositoryBase
from core.restclient.v2_0.agilitymodel.base.Item import ItemBase
from core.restclient.v2_0.agilitymodel.base.Image import ImageBase
from core.restclient.v2_0.agilitymodel.base.ErrorMessage import ErrorMessageBase
from core.restclient.v2_0.agilitymodel.base.PropertyDefinitionGroup import PropertyDefinitionGroupBase
from core.restclient.v2_0.agilitymodel.base.StoreReview import StoreReviewBase
from core.restclient.v2_0.agilitymodel.base.LaunchItem import LaunchItemBase
from core.restclient.v2_0.agilitymodel.base.PlatformService import PlatformServiceBase
from core.restclient.v2_0.agilitymodel.base.OnboardRequest import OnboardRequestBase
from core.restclient.v2_0.agilitymodel.base.DeploymentBinding import DeploymentBindingBase
from core.restclient.v2_0.agilitymodel.base.SolutionDeploymentConfig import SolutionDeploymentConfigBase
from core.restclient.v2_0.agilitymodel.base.RegexValidator import RegexValidatorBase
from core.restclient.v2_0.agilitymodel.base.Environment import EnvironmentBase
from core.restclient.v2_0.agilitymodel.base.Instance import InstanceBase
from core.restclient.v2_0.agilitymodel.base.ResourceRank import ResourceRankBase
from core.restclient.v2_0.agilitymodel.base.Attachment import AttachmentBase
from core.restclient.v2_0.agilitymodel.base.ProjectRole import ProjectRoleBase
from core.restclient.v2_0.agilitymodel.base.InputVariable import InputVariableBase
from core.restclient.v2_0.agilitymodel.base.ServiceBinding import ServiceBindingBase
from core.restclient.v2_0.agilitymodel.base.DateValidator import DateValidatorBase
from core.restclient.v2_0.agilitymodel.base.PolicyMeta import PolicyMetaBase
from core.restclient.v2_0.agilitymodel.base.ScriptClasspath import ScriptClasspathBase
from core.restclient.v2_0.agilitymodel.base.Network import NetworkBase
from core.restclient.v2_0.agilitymodel.base.Blueprint import BlueprintBase
from core.restclient.v2_0.agilitymodel.base.AuthenticationType import AuthenticationTypeBase
from core.restclient.v2_0.agilitymodel.base.FieldMeta import FieldMetaBase
from core.restclient.v2_0.agilitymodel.base.PropertyDefinitionReference import PropertyDefinitionReferenceBase
from core.restclient.v2_0.agilitymodel.base.Assetlist import AssetlistBase
from core.restclient.v2_0.agilitymodel.base.ObjectReference import ObjectReferenceBase
from core.restclient.v2_0.agilitymodel.base.User import UserBase
from core.restclient.v2_0.agilitymodel.base.Variable import VariableBase
from core.restclient.v2_0.agilitymodel.base.StringLengthValidator import StringLengthValidatorBase
from core.restclient.v2_0.agilitymodel.base.AccessRight import AccessRightBase
from core.restclient.v2_0.agilitymodel.base.Topology import TopologyBase
from core.restclient.v2_0.agilitymodel.base.WorkflowTask import WorkflowTaskBase
from core.restclient.v2_0.agilitymodel.base.FieldValidator import FieldValidatorBase
from core.restclient.v2_0.agilitymodel.base.Commands import CommandsBase
from core.restclient.v2_0.agilitymodel.base.ConfigurationResource import ConfigurationResourceBase
from core.restclient.v2_0.agilitymodel.base.TreeNode import TreeNodeBase
from core.restclient.v2_0.agilitymodel.base.EmailValidator import EmailValidatorBase
from core.restclient.v2_0.agilitymodel.base.StorePublisher import StorePublisherBase
from core.restclient.v2_0.agilitymodel.base.ResourceWeightMeta import ResourceWeightMetaBase
from core.restclient.v2_0.agilitymodel.base.PolicyAssignment import PolicyAssignmentBase
from core.restclient.v2_0.agilitymodel.base.AttachmentLocation import AttachmentLocationBase
from core.restclient.v2_0.agilitymodel.base.Connection import ConnectionBase
from core.restclient.v2_0.agilitymodel.base.Snapshot import SnapshotBase
from core.restclient.v2_0.agilitymodel.base.ArtifactConfiguration import ArtifactConfigurationBase
from core.restclient.v2_0.agilitymodel.base.SolutionDeployment import SolutionDeploymentBase
from core.restclient.v2_0.agilitymodel.base.ConfigurationArtifact import ConfigurationArtifactBase
from core.restclient.v2_0.agilitymodel.base.NumericRangeValidator import NumericRangeValidatorBase
from core.restclient.v2_0.agilitymodel.base.AssetMatch import AssetMatchBase
from core.restclient.v2_0.agilitymodel.base.StoreEdition import StoreEditionBase
from core.restclient.v2_0.agilitymodel.base.StoreCatalog import StoreCatalogBase
from core.restclient.v2_0.agilitymodel.base.Rating import RatingBase
from core.restclient.v2_0.agilitymodel.base.ResourceMetric import ResourceMetricBase
from core.restclient.v2_0.agilitymodel.base.DesignAlias import DesignAliasBase
from core.restclient.v2_0.agilitymodel.base.ConfigurationArtifactType import ConfigurationArtifactTypeBase
from core.restclient.v2_0.agilitymodel.base.PolicyType import PolicyTypeBase
from core.restclient.v2_0.agilitymodel.base.AgilityVersion import AgilityVersionBase
from core.restclient.v2_0.agilitymodel.base.AccessUriList import AccessUriListBase
from core.restclient.v2_0.agilitymodel.base.CloudType import CloudTypeBase
from core.restclient.v2_0.agilitymodel.base.ScriptStatus import ScriptStatusBase
from core.restclient.v2_0.agilitymodel.base.WorkflowMeta import WorkflowMetaBase
from core.restclient.v2_0.agilitymodel.base.ScriptPropertyReference import ScriptPropertyReferenceBase
from core.restclient.v2_0.agilitymodel.base.Container import ContainerBase
from core.restclient.v2_0.agilitymodel.base.DesignConnection import DesignConnectionBase
from core.restclient.v2_0.agilitymodel.base.VersionedItem import VersionedItemBase
from core.restclient.v2_0.agilitymodel.base.NumericScaleValidator import NumericScaleValidatorBase
from core.restclient.v2_0.agilitymodel.base.DhcpOptions import DhcpOptionsBase
from core.restclient.v2_0.agilitymodel.base.StoreProductAdapterItem import StoreProductAdapterItemBase
from core.restclient.v2_0.agilitymodel.base.DesignDeployer import DesignDeployerBase
from core.restclient.v2_0.agilitymodel.base.CustomContainer import CustomContainerBase
from core.restclient.v2_0.agilitymodel.base.ValueProvider import ValueProviderBase
from core.restclient.v2_0.agilitymodel.base.Policy import PolicyBase
from core.restclient.v2_0.agilitymodel.base.DeploymentRequest import DeploymentRequestBase
from core.restclient.v2_0.agilitymodel.base.StoreRelease import StoreReleaseBase
from core.restclient.v2_0.agilitymodel.base.AddressRangeList import AddressRangeListBase
from core.restclient.v2_0.agilitymodel.base.PlanEvalRequest import PlanEvalRequestBase
from core.restclient.v2_0.agilitymodel.base.DeploymentPlan import DeploymentPlanBase
from core.restclient.v2_0.agilitymodel.base.VolumeStorageSnapshot import VolumeStorageSnapshotBase
from core.restclient.v2_0.agilitymodel.base.NetworkService import NetworkServiceBase
from core.restclient.v2_0.agilitymodel.base.ResourceWeight import ResourceWeightBase
from core.restclient.v2_0.agilitymodel.base.Tasklist import TasklistBase
from core.restclient.v2_0.agilitymodel.base.CustomContainerList import CustomContainerListBase
from core.restclient.v2_0.agilitymodel.base.DeploymentPolicyMeta import DeploymentPolicyMetaBase
from core.restclient.v2_0.agilitymodel.base.ScriptLanguage import ScriptLanguageBase
from core.restclient.v2_0.agilitymodel.base.ArtifactType import ArtifactTypeBase
from core.restclient.v2_0.agilitymodel.base.WorkflowTransitionMeta import WorkflowTransitionMetaBase
from core.restclient.v2_0.agilitymodel.base.Envelope import EnvelopeBase
from core.restclient.v2_0.agilitymodel.base.AssetFilter import AssetFilterBase
from core.restclient.v2_0.agilitymodel.base.Artifact import ArtifactBase
from core.restclient.v2_0.agilitymodel.base.OperatingSystem import OperatingSystemBase
from core.restclient.v2_0.agilitymodel.base.Volume import VolumeBase
from core.restclient.v2_0.agilitymodel.base.WorkflowRequest import WorkflowRequestBase
from core.restclient.v2_0.agilitymodel.base.VariableList import VariableListBase
from core.restclient.v2_0.agilitymodel.base.Proxy import ProxyBase
from core.restclient.v2_0.agilitymodel.base.Deployment import DeploymentBase
from core.restclient.v2_0.agilitymodel.base.PlatformServiceType import PlatformServiceTypeBase
from core.restclient.v2_0.agilitymodel.base.PropertyTypeValue import PropertyTypeValueBase
from core.restclient.v2_0.agilitymodel.base.Stack import StackBase
from core.restclient.v2_0.agilitymodel.base.LogicalLink import LogicalLinkBase
from core.restclient.v2_0.agilitymodel.base.ContainerRights import ContainerRightsBase
from core.restclient.v2_0.agilitymodel.base.StoreCategory import StoreCategoryBase
from core.restclient.v2_0.agilitymodel.base.Resource import ResourceBase
from core.restclient.v2_0.agilitymodel.base.SecurityRole import SecurityRoleBase
from core.restclient.v2_0.agilitymodel.base.Package import PackageBase
from core.restclient.v2_0.agilitymodel.base.DesignContainer import DesignContainerBase
from core.restclient.v2_0.agilitymodel.base.ResourceMapping import ResourceMappingBase
from core.restclient.v2_0.agilitymodel.base.LaunchItemDeployment import LaunchItemDeploymentBase
from core.restclient.v2_0.agilitymodel.base.NetworkInterface import NetworkInterfaceBase
from core.restclient.v2_0.agilitymodel.base.Alias import AliasBase
from core.restclient.v2_0.agilitymodel.base.SearchTree import SearchTreeBase
from core.restclient.v2_0.agilitymodel.base.Model import ModelBase
from core.restclient.v2_0.agilitymodel.base.Runtime import RuntimeBase
from core.restclient.v2_0.agilitymodel.base.EffectiveProtocol import EffectiveProtocolBase
from core.restclient.v2_0.agilitymodel.base.VolumeStorage import VolumeStorageBase
from core.restclient.v2_0.agilitymodel.base.CustomItemList import CustomItemListBase
from core.restclient.v2_0.agilitymodel.base.InputVariableRequest import InputVariableRequestBase
from core.restclient.v2_0.agilitymodel.base.WorkflowTaskList import WorkflowTaskListBase
from core.restclient.v2_0.agilitymodel.base.ConfigurationRepository import ConfigurationRepositoryBase
from core.restclient.v2_0.agilitymodel.base.TopologyStats import TopologyStatsBase
from core.restclient.v2_0.agilitymodel.base.Solution import SolutionBase
from core.restclient.v2_0.agilitymodel.base.ArtifactRuntimeBinding import ArtifactRuntimeBindingBase
from core.restclient.v2_0.agilitymodel.base.PolicyMetaModel import PolicyMetaModelBase
from core.restclient.v2_0.agilitymodel.base.PropertyType import PropertyTypeBase
from core.restclient.v2_0.agilitymodel.base.ErrorInfo import ErrorInfoBase
from core.restclient.v2_0.agilitymodel.base.NumericRange import NumericRangeBase
from core.restclient.v2_0.agilitymodel.base.PropertyDefinitionList import PropertyDefinitionListBase
from core.restclient.v2_0.agilitymodel.base.Cloud import CloudBase
from core.restclient.v2_0.agilitymodel.base.FileSystemDevice import FileSystemDeviceBase
__all__ = ['EULABase', 'NetworkServiceTypeBase', 'PropertyDefinitionBase', 'StorePriceBase', 'ConfigurationPolicyMetaBase', 'IntegerRangeValidatorBase', 'AccessListBase', 'AuthenticationBase', 'AssetBase', 'TemplateBase', 'ConfigPropertyBase', 'IntegerScaleValidatorBase', 'ResourceWeightInfoBase', 'CredentialBase', 'EffectiveProtocolRequestBase', 'ResourceMetricsBase', 'BlueprintRefBase', 'IntegerRangeBase', 'HostBase', 'AddressListBase', 'VersionListBase', 'StoreProductTypeBase', 'ResourcePolicyBase', 'WorkflowTaskMetaBase', 'CloudMetaModelBase', 'AccessRightSetBase', 'TaskBase', 'ConfigSettingsBase', 'AddressBase', 'CustomItemBase', 'ProjectBase', 'NameValuePairBase', 'StoreProductAdapterItemListBase', 'OnboardMetaBase', 'EnvironmentTypeBase', 'PriceEngineBase', 'ImportDirectivesBase', 'VersionedItemLinkBase', 'ProtocolBase', 'TaxonomyBase', 'DeploymentArtifactConfigBase', 'PublishRequestBase', 'ServiceBindingTypeBase', 'DesignItemBase', 'TargetCloudBase', 'AssetPropertyBase', 'LifecyclePolicyMetaBase', 'AssetTypeBriefBase', 'ResourceMatchBase', 'StorageSnapshotBase', 'LdapGroupListBase', 'StoreResourceBase', 'ScriptBase', 'NetworkInterfaceListBase', 'StorageBase', 'AssetTypeMetaBase', 'LocationBase', 'ArtifactAttachmentBase', 'PropertyMatchBase', 'ParameterBase', 'AssetTypeListBase', 'DeployerBase', 'InputVariableListBase', 'StoreProductAdapterBase', 'LinkBase', 'StoreReleaseTypeBase', 'FileSystemBase', 'ResourceWeightMetaListBase', 'DeploymentConfigurationBase', 'PermissionTypeBase', 'StoreProductBase', 'AliasListBase', 'AssetTypeBase', 'WorkloadBase', 'AccessUriBase', 'StoreEditionTypeBase', 'LdapGroupBase', 'AddressRangeBase', 'VariableValueSetBase', 'LinklistBase', 'CommandBase', 'UserGroupBase', 'ItemLinkBase', 'PropertyBase', 'CommentBase', 'DomainBase', 'RepositoryBase', 'ItemBase', 'ImageBase', 'ErrorMessageBase', 'PropertyDefinitionGroupBase', 'StoreReviewBase', 'LaunchItemBase', 'PlatformServiceBase', 'OnboardRequestBase', 'DeploymentBindingBase', 'SolutionDeploymentConfigBase', 'RegexValidatorBase', 'EnvironmentBase', 'InstanceBase', 'ResourceRankBase', 'AttachmentBase', 'ProjectRoleBase', 'InputVariableBase', 'ServiceBindingBase', 'DateValidatorBase', 'PolicyMetaBase', 'ScriptClasspathBase', 'NetworkBase', 'BlueprintBase', 'AuthenticationTypeBase', 'FieldMetaBase', 'PropertyDefinitionReferenceBase', 'AssetlistBase', 'ObjectReferenceBase', 'UserBase', 'VariableBase', 'StringLengthValidatorBase', 'AccessRightBase', 'TopologyBase', 'WorkflowTaskBase', 'FieldValidatorBase', 'CommandsBase', 'ConfigurationResourceBase', 'TreeNodeBase', 'EmailValidatorBase', 'StorePublisherBase', 'ResourceWeightMetaBase', 'PolicyAssignmentBase', 'AttachmentLocationBase', 'ConnectionBase', 'SnapshotBase', 'ArtifactConfigurationBase', 'SolutionDeploymentBase', 'ConfigurationArtifactBase', 'NumericRangeValidatorBase', 'AssetMatchBase', 'StoreEditionBase', 'StoreCatalogBase', 'RatingBase', 'ResourceMetricBase', 'DesignAliasBase', 'ConfigurationArtifactTypeBase', 'PolicyTypeBase', 'AgilityVersionBase', 'AccessUriListBase', 'CloudTypeBase', 'ScriptStatusBase', 'WorkflowMetaBase', 'ScriptPropertyReferenceBase', 'ContainerBase', 'DesignConnectionBase', 'VersionedItemBase', 'NumericScaleValidatorBase', 'DhcpOptionsBase', 'StoreProductAdapterItemBase', 'DesignDeployerBase', 'CustomContainerBase', 'ValueProviderBase', 'PolicyBase', 'DeploymentRequestBase', 'StoreReleaseBase', 'AddressRangeListBase', 'PlanEvalRequestBase', 'DeploymentPlanBase', 'VolumeStorageSnapshotBase', 'NetworkServiceBase', 'ResourceWeightBase', 'TasklistBase', 'CustomContainerListBase', 'DeploymentPolicyMetaBase', 'ScriptLanguageBase', 'ArtifactTypeBase', 'WorkflowTransitionMetaBase', 'EnvelopeBase', 'AssetFilterBase', 'ArtifactBase', 'OperatingSystemBase', 'VolumeBase', 'WorkflowRequestBase', 'VariableListBase', 'ProxyBase', 'DeploymentBase', 'PlatformServiceTypeBase', 'PropertyTypeValueBase', 'StackBase', 'LogicalLinkBase', 'ContainerRightsBase', 'StoreCategoryBase', 'ResourceBase', 'SecurityRoleBase', 'PackageBase', 'DesignContainerBase', 'ResourceMappingBase', 'LaunchItemDeploymentBase', 'NetworkInterfaceBase', 'AliasBase', 'SearchTreeBase', 'ModelBase', 'RuntimeBase', 'EffectiveProtocolBase', 'VolumeStorageBase', 'CustomItemListBase', 'InputVariableRequestBase', 'WorkflowTaskListBase', 'ConfigurationRepositoryBase', 'TopologyStatsBase', 'SolutionBase', 'ArtifactRuntimeBindingBase', 'PolicyMetaModelBase', 'PropertyTypeBase', 'ErrorInfoBase', 'NumericRangeBase', 'PropertyDefinitionListBase', 'CloudBase', 'FileSystemDeviceBase']