
from core.base.enum import Enum

RepositoryUsage = Enum(**{'VM_ARTIFACTS': 'VM_ARTIFACTS', 'VM_INSTANCES': 'VM_INSTANCES', 'VM_ATTACHMENTS': 'VM_ATTACHMENTS', 'VM_NONE': 'VM_NONE', 'VM_TEMPLATES': 'VM_TEMPLATES', 'VM_STORAGE': 'VM_STORAGE', 'VM_BACKUPS': 'VM_BACKUPS'})
