
from core.base.enum import Enum

ProxyUsage = Enum(**{'PROXY_MANAGER_CLOUD': 'PROXY_MANAGER_CLOUD', 'PROXY_INSTANCE_PROVIDER': 'PROXY_INSTANCE_PROVIDER', 'PROXY_MANAGER_INSTANCE': 'PROXY_MANAGER_INSTANCE', 'PROXY_ALL': 'PROXY_ALL', 'PROXY_CLIENTS_INSTANCE': 'PROXY_CLIENTS_INSTANCE'})
