'''
Created on Apr 9, 2013

@author: dawood
'''
duplicateMethods = {'/artifacttype_getType_artifacttype/{id}_{}_id': {'Content-Type': {},
                                                   'class': '/artifacttype',
                                                   'method_alias': 'getTypeById',
                                                   'name': 'getType',
                                                   'path': 'artifacttype/{id}',
                                                   'path_param_names': 'id',
                                                   'path_params': [{'alias': 'artifacttype_id',
                                                                    'defaultValue': None,
                                                                    'kind': 'xs:int',
                                                                    'name': 'id',
                                                                    'required': False}]},
 '/artifacttype_getType_artifacttype_{}_': {'Content-Type': {},
                                            'class': '/artifacttype',
                                            'method_alias': 'getType',
                                            'name': 'getType',
                                            'path': 'artifacttype',
                                            'path_param_names': '',
                                            'path_params': []},
 "/assettype_importAction_assettype/import_{'Content-Type': 'application/x-zip'}_": {'Content-Type': {'Content-Type': 'application/x-zip'},
                                                                                     'class': '/assettype',
                                                                                     'method_alias': 'importAction',
                                                                                     'name': 'importAction',
                                                                                     'path': 'assettype/import',
                                                                                     'path_param_names': '',
                                                                                     'path_params': []},
 "/assettype_importAction_assettype/import_{'Content-Type': 'application/xml'}_": {'Content-Type': {'Content-Type': 'application/xml'},
                                                                                   'class': '/assettype',
                                                                                   'method_alias': 'importActionXML',
                                                                                   'name': 'importAction',
                                                                                   'path': 'assettype/import',
                                                                                   'path_param_names': '',
                                                                                   'path_params': []},
 "/blueprint_checkIn_blueprint/{id}/checkin/{locationId}_{'Content-Type': 'application/xml'}_id_locationId": {'Content-Type': {'Content-Type': 'application/xml'},
                                                                                                              'class': '/blueprint',
                                                                                                              'method_alias': 'checkInByLocation',
                                                                                                              'name': 'checkIn',
                                                                                                              'path': 'blueprint/{id}/checkin/{locationId}',
                                                                                                              'path_param_names': 'id_locationId',
                                                                                                              'path_params': [{'alias': 'blueprint_id',
                                                                                                                               'defaultValue': None,
                                                                                                                               'kind': 'xs:int',
                                                                                                                               'name': 'id',
                                                                                                                               'required': True},
                                                                                                                              {'alias': 'checkin_locationId',
                                                                                                                               'defaultValue': None,
                                                                                                                               'kind': 'xs:int',
                                                                                                                               'name': 'locationId',
                                                                                                                               'required': False}]},
 "/blueprint_checkIn_blueprint/{id}/checkin_{'Content-Type': 'application/xml'}_id": {'Content-Type': {'Content-Type': 'application/xml'},
                                                                                      'class': '/blueprint',
                                                                                      'method_alias': 'checkIn',
                                                                                      'name': 'checkIn',
                                                                                      'path': 'blueprint/{id}/checkin',
                                                                                      'path_param_names': 'id',
                                                                                      'path_params': [{'alias': 'blueprint_id',
                                                                                                       'defaultValue': None,
                                                                                                       'kind': 'xs:int',
                                                                                                       'name': 'id',
                                                                                                       'required': True}]},
 "/blueprint_deploy_blueprint/{id}/deploy/{containerId}_{'Content-Type': '*/*'}_id_containerId": {'Content-Type': {'Content-Type': '*/*'},
                                                                                                  'class': '/blueprint',
                                                                                                  'method_alias': 'deploy',
                                                                                                  'name': 'deploy',
                                                                                                  'path': 'blueprint/{id}/deploy/{containerId}',
                                                                                                  'path_param_names': 'id_containerId',
                                                                                                  'path_params': [{'alias': 'blueprint_id',
                                                                                                                   'defaultValue': None,
                                                                                                                   'kind': 'xs:int',
                                                                                                                   'name': 'id',
                                                                                                                   'required': True},
                                                                                                                  {'alias': 'deploy_containerId',
                                                                                                                   'defaultValue': None,
                                                                                                                   'kind': 'xs:int',
                                                                                                                   'name': 'containerId',
                                                                                                                   'required': False}]},
 '/blueprint_deploy_blueprint/{id}/deploy/{containerId}_{}_id_containerId': {'Content-Type': {},
                                                                             'class': '/blueprint',
                                                                             'method_alias': 'deploy2',
                                                                             'name': 'deploy',
                                                                             'path': 'blueprint/{id}/deploy/{containerId}',
                                                                             'path_param_names': 'id_containerId',
                                                                             'path_params': [{'alias': 'blueprint_id',
                                                                                              'defaultValue': None,
                                                                                              'kind': 'xs:int',
                                                                                              'name': 'id',
                                                                                              'required': True},
                                                                                             {'alias': 'deploy_containerId',
                                                                                              'defaultValue': None,
                                                                                              'kind': 'xs:int',
                                                                                              'name': 'containerId',
                                                                                              'required': False}]},
 '/compute_updateAlias_compute/{id}/alias/{alias_id: [0-9]+}_{}_id_alias_id': {'Content-Type': {},
                                                                               'class': '/compute',
                                                                               'method_alias': 'updateAlias',
                                                                               'name': 'updateAlias',
                                                                               'path': 'compute/{id}/alias/{alias_id: [0-9]+}',
                                                                               'path_param_names': 'id_alias_id',
                                                                               'path_params': [{'alias': 'compute_id',
                                                                                                'defaultValue': None,
                                                                                                'kind': 'xs:int',
                                                                                                'name': 'id',
                                                                                                'required': True},
                                                                                               {'alias': 'alias_id',
                                                                                                'defaultValue': None,
                                                                                                'kind': 'xs:int',
                                                                                                'name': 'alias_id',
                                                                                                'required': False}]},
 '/compute_updateAlias_compute/{id}/alias/{name: [a-zA-Z0-9_\\-]+}_{}_id_name': {'Content-Type': {},
                                                                                 'class': '/compute',
                                                                                 'method_alias': 'updateAliasByName',
                                                                                 'name': 'updateAlias',
                                                                                 'path': 'compute/{id}/alias/{name: [a-zA-Z0-9_\\-]+}',
                                                                                 'path_param_names': 'id_name',
                                                                                 'path_params': [{'alias': 'compute_id',
                                                                                                  'defaultValue': None,
                                                                                                  'kind': 'xs:int',
                                                                                                  'name': 'id',
                                                                                                  'required': True},
                                                                                                 {'alias': 'alias_name',
                                                                                                  'defaultValue': None,
                                                                                                  'kind': 'xs:string',
                                                                                                  'name': 'name',
                                                                                                  'required': False}]},
 "/configuration/artifact_importAction_configuration/artifact/import_{'Content-Type': 'application/x-zip'}_": {'Content-Type': {'Content-Type': 'application/x-zip'},
                                                                                                               'class': '/configuration/artifact',
                                                                                                               'method_alias': 'importAction',
                                                                                                               'name': 'importAction',
                                                                                                               'path': 'configuration/artifact/import',
                                                                                                               'path_param_names': '',
                                                                                                               'path_params': []},
 "/configuration/artifact_importAction_configuration/artifact/import_{'Content-Type': 'application/xml'}_": {'Content-Type': {'Content-Type': 'application/xml'},
                                                                                                             'class': '/configuration/artifact',
                                                                                                             'method_alias': 'importActionXML',
                                                                                                             'name': 'importAction',
                                                                                                             'path': 'configuration/artifact/import',
                                                                                                             'path_param_names': '',
                                                                                                             'path_params': []},
 "/configuration/repository_importAction_configuration/repository/import_{'Content-Type': 'application/x-zip'}_": {'Content-Type': {'Content-Type': 'application/x-zip'},
                                                                                                                   'class': '/configuration/repository',
                                                                                                                   'method_alias': 'importAction',
                                                                                                                   'name': 'importAction',
                                                                                                                   'path': 'configuration/repository/import',
                                                                                                                   'path_param_names': '',
                                                                                                                   'path_params': []},
 "/configuration/repository_importAction_configuration/repository/import_{'Content-Type': 'application/xml'}_": {'Content-Type': {'Content-Type': 'application/xml'},
                                                                                                                 'class': '/configuration/repository',
                                                                                                                 'method_alias': 'importActionXML',
                                                                                                                 'name': 'importAction',
                                                                                                                 'path': 'configuration/repository/import',
                                                                                                                 'path_param_names': '',
                                                                                                                 'path_params': []},
 "/configuration/resource_getResource_configuration/resource/{id}_{'Content-Type': 'application/xml'}_id": {'Content-Type': {'Content-Type': 'application/xml'},
                                                                                                            'class': '/configuration/resource',
                                                                                                            'method_alias': 'getResourceXML',
                                                                                                            'name': 'getResource',
                                                                                                            'path': 'configuration/resource/{id}',
                                                                                                            'path_param_names': 'id',
                                                                                                            'path_params': [{'alias': 'resource_id',
                                                                                                                             'defaultValue': None,
                                                                                                                             'kind': 'xs:int',
                                                                                                                             'name': 'id',
                                                                                                                             'required': False}]},
 '/configuration/resource_getResource_configuration/resource/{id}_{}_id': {'Content-Type': {},
                                                                           'class': '/configuration/resource',
                                                                           'method_alias': 'getResource',
                                                                           'name': 'getResource',
                                                                           'path': 'configuration/resource/{id}',
                                                                           'path_param_names': 'id',
                                                                           'path_params': [{'alias': 'resource_id',
                                                                                            'defaultValue': None,
                                                                                            'kind': 'xs:int',
                                                                                            'name': 'id',
                                                                                            'required': False}]},
 "/configuration/resource_importAction_configuration/resource/import_{'Content-Type': 'application/x-zip'}_": {'Content-Type': {'Content-Type': 'application/x-zip'},
                                                                                                               'class': '/configuration/resource',
                                                                                                               'method_alias': 'importAction',
                                                                                                               'name': 'importAction',
                                                                                                               'path': 'configuration/resource/import',
                                                                                                               'path_param_names': '',
                                                                                                               'path_params': []},
 "/configuration/resource_importAction_configuration/resource/import_{'Content-Type': 'application/xml'}_": {'Content-Type': {'Content-Type': 'application/xml'},
                                                                                                             'class': '/configuration/resource',
                                                                                                             'method_alias': 'importActionXML',
                                                                                                             'name': 'importAction',
                                                                                                             'path': 'configuration/resource/import',
                                                                                                             'path_param_names': '',
                                                                                                             'path_params': []},
 '/container_getContainers_container/{id}/container_{}_id': {'Content-Type': {},
                                                             'class': '/container',
                                                             'method_alias': 'getContainersById',
                                                             'name': 'getContainers',
                                                             'path': 'container/{id}/container',
                                                             'path_param_names': 'id',
                                                             'path_params': [{'alias': 'container_id',
                                                                              'defaultValue': None,
                                                                              'kind': 'xs:int',
                                                                              'name': 'id',
                                                                              'required': True}]},
 '/container_getContainers_container_{}_': {'Content-Type': {},
                                            'class': '/container',
                                            'method_alias': 'getContainers',
                                            'name': 'getContainers',
                                            'path': 'container',
                                            'path_param_names': '',
                                            'path_params': []},
 "/container_importAction_container/import_{'Content-Type': 'application/x-zip'}_": {'Content-Type': {'Content-Type': 'application/x-zip'},
                                                                                     'class': '/container',
                                                                                     'method_alias': 'importAction',
                                                                                     'name': 'importAction',
                                                                                     'path': 'container/import',
                                                                                     'path_param_names': '',
                                                                                     'path_params': []},
 "/container_importAction_container/import_{'Content-Type': 'application/xml'}_": {'Content-Type': {'Content-Type': 'application/xml'},
                                                                                   'class': '/container',
                                                                                   'method_alias': 'importActionXML',
                                                                                   'name': 'importAction',
                                                                                   'path': 'container/import',
                                                                                   'path_param_names': '',
                                                                                   'path_params': []},
 "/container_importIDAction_container/{id}/import_{'Content-Type': 'application/x-zip'}_id": {'Content-Type': {'Content-Type': 'application/x-zip'},
                                                                                              'class': '/container',
                                                                                              'method_alias': 'importIDAction',
                                                                                              'name': 'importIDAction',
                                                                                              'path': 'container/{id}/import',
                                                                                              'path_param_names': 'id',
                                                                                              'path_params': [{'alias': 'container_id',
                                                                                                               'defaultValue': None,
                                                                                                               'kind': 'xs:int',
                                                                                                               'name': 'id',
                                                                                                               'required': True}]},
 "/container_importIDAction_container/{id}/import_{'Content-Type': 'application/xml'}_id": {'Content-Type': {'Content-Type': 'application/xml'},
                                                                                            'class': '/container',
                                                                                            'method_alias': 'importIDActionXML',
                                                                                            'name': 'importIDAction',
                                                                                            'path': 'container/{id}/import',
                                                                                            'path_param_names': 'id',
                                                                                            'path_params': [{'alias': 'container_id',
                                                                                                             'defaultValue': None,
                                                                                                             'kind': 'xs:int',
                                                                                                             'name': 'id',
                                                                                                             'required': True}]},
 '/credential_getCredential2_credential/{id}/decrypt/{field}_{}_id_field': {'Content-Type': {},
                                                                            'class': '/credential',
                                                                            'method_alias': 'getCredential2Field',
                                                                            'name': 'getCredential2',
                                                                            'path': 'credential/{id}/decrypt/{field}',
                                                                            'path_param_names': 'id_field',
                                                                            'path_params': [{'alias': 'credential_id',
                                                                                             'defaultValue': None,
                                                                                             'kind': 'xs:int',
                                                                                             'name': 'id',
                                                                                             'required': True},
                                                                                            {'alias': 'decrypt_field',
                                                                                             'defaultValue': None,
                                                                                             'kind': 'xs:string',
                                                                                             'name': 'field',
                                                                                             'required': False}]},
 '/credential_getCredential2_credential/{id}/decrypt_{}_id': {'Content-Type': {},
                                                              'class': '/credential',
                                                              'method_alias': 'getCredential2',
                                                              'name': 'getCredential2',
                                                              'path': 'credential/{id}/decrypt',
                                                              'path_param_names': 'id',
                                                              'path_params': [{'alias': 'credential_id',
                                                                               'defaultValue': None,
                                                                               'kind': 'xs:int',
                                                                               'name': 'id',
                                                                               'required': True}]},
 "/customcontainer_importAction_customcontainer/import_{'Content-Type': 'application/x-zip'}_": {'Content-Type': {'Content-Type': 'application/x-zip'},
                                                                                                 'class': '/customcontainer',
                                                                                                 'method_alias': 'importAction',
                                                                                                 'name': 'importAction',
                                                                                                 'path': 'customcontainer/import',
                                                                                                 'path_param_names': '',
                                                                                                 'path_params': []},
 "/customcontainer_importAction_customcontainer/import_{'Content-Type': 'application/xml'}_": {'Content-Type': {'Content-Type': 'application/xml'},
                                                                                               'class': '/customcontainer',
                                                                                               'method_alias': 'importActionXML',
                                                                                               'name': 'importAction',
                                                                                               'path': 'customcontainer/import',
                                                                                               'path_param_names': '',
                                                                                               'path_params': []},
 "/customcontainer_importIDAction_customcontainer/{id}/import_{'Content-Type': 'application/x-zip'}_id": {'Content-Type': {'Content-Type': 'application/x-zip'},
                                                                                                          'class': '/customcontainer',
                                                                                                          'method_alias': 'importIDAction',
                                                                                                          'name': 'importIDAction',
                                                                                                          'path': 'customcontainer/{id}/import',
                                                                                                          'path_param_names': 'id',
                                                                                                          'path_params': [{'alias': 'customcontainer_id',
                                                                                                                           'defaultValue': None,
                                                                                                                           'kind': 'xs:int',
                                                                                                                           'name': 'id',
                                                                                                                           'required': True}]},
 "/customcontainer_importIDAction_customcontainer/{id}/import_{'Content-Type': 'application/xml'}_id": {'Content-Type': {'Content-Type': 'application/xml'},
                                                                                                        'class': '/customcontainer',
                                                                                                        'method_alias': 'importIDActionXML',
                                                                                                        'name': 'importIDAction',
                                                                                                        'path': 'customcontainer/{id}/import',
                                                                                                        'path_param_names': 'id',
                                                                                                        'path_params': [{'alias': 'customcontainer_id',
                                                                                                                         'defaultValue': None,
                                                                                                                         'kind': 'xs:int',
                                                                                                                         'name': 'id',
                                                                                                                         'required': True}]},
 "/environment_importIDAction_environment/{id}/import_{'Content-Type': 'application/x-zip'}_id": {'Content-Type': {'Content-Type': 'application/x-zip'},
                                                                                                  'class': '/environment',
                                                                                                  'method_alias': 'importIDAction',
                                                                                                  'name': 'importIDAction',
                                                                                                  'path': 'environment/{id}/import',
                                                                                                  'path_param_names': 'id',
                                                                                                  'path_params': [{'alias': 'environment_id',
                                                                                                                   'defaultValue': None,
                                                                                                                   'kind': 'xs:int',
                                                                                                                   'name': 'id',
                                                                                                                   'required': True}]},
 "/environment_importIDAction_environment/{id}/import_{'Content-Type': 'application/xml'}_id": {'Content-Type': {'Content-Type': 'application/xml'},
                                                                                                'class': '/environment',
                                                                                                'method_alias': 'importIDActionXML',
                                                                                                'name': 'importIDAction',
                                                                                                'path': 'environment/{id}/import',
                                                                                                'path_param_names': 'id',
                                                                                                'path_params': [{'alias': 'environment_id',
                                                                                                                 'defaultValue': None,
                                                                                                                 'kind': 'xs:int',
                                                                                                                 'name': 'id',
                                                                                                                 'required': True}]},
 '/launchitem_deploy_launchitem/{id}/deploy/{locationId}_{}_id_locationId': {'Content-Type': {},
                                                                             'class': '/launchitem',
                                                                             'method_alias': 'deployByLocation',
                                                                             'name': 'deploy',
                                                                             'path': 'launchitem/{id}/deploy/{locationId}',
                                                                             'path_param_names': 'id_locationId',
                                                                             'path_params': [{'alias': 'launchitem_id',
                                                                                              'defaultValue': None,
                                                                                              'kind': 'xs:int',
                                                                                              'name': 'id',
                                                                                              'required': True},
                                                                                             {'alias': 'deploy_locationId',
                                                                                              'defaultValue': None,
                                                                                              'kind': 'xs:int',
                                                                                              'name': 'locationId',
                                                                                              'required': False}]},
 "/launchitem_deploy_launchitem/{id}/deploy_{'Content-Type': 'application/xml'}_id": {'Content-Type': {'Content-Type': 'application/xml'},
                                                                                      'class': '/launchitem',
                                                                                      'method_alias': 'deploy',
                                                                                      'name': 'deploy',
                                                                                      'path': 'launchitem/{id}/deploy',
                                                                                      'path_param_names': 'id',
                                                                                      'path_params': [{'alias': 'launchitem_id',
                                                                                                       'defaultValue': None,
                                                                                                       'kind': 'xs:int',
                                                                                                       'name': 'id',
                                                                                                       'required': True}]},
 '/ldapgroup_createMapping_ldapgroup/{ldapGpName}/{agilityGpName}_{}_ldapGpName_agilityGpName': {'Content-Type': {},
                                                                                                 'class': '/ldapgroup',
                                                                                                 'method_alias': 'createMapping',
                                                                                                 'name': 'createMapping',
                                                                                                 'path': 'ldapgroup/{ldapGpName}/{agilityGpName}',
                                                                                                 'path_param_names': 'ldapGpName_agilityGpName',
                                                                                                 'path_params': [{'alias': 'ldapgroup_ldapGpName',
                                                                                                                  'defaultValue': None,
                                                                                                                  'kind': 'xs:string',
                                                                                                                  'name': 'ldapGpName',
                                                                                                                  'required': True},
                                                                                                                 {'alias': 'agilityGpName',
                                                                                                                  'defaultValue': None,
                                                                                                                  'kind': 'xs:string',
                                                                                                                  'name': 'agilityGpName',
                                                                                                                  'required': False}]},
 "/ldapgroup_createMapping_ldapgroup_{'Content-Type': 'application/xml'}_": {'Content-Type': {'Content-Type': 'application/xml'},
                                                                             'class': '/ldapgroup',
                                                                             'method_alias': 'createMappingXML',
                                                                             'name': 'createMapping',
                                                                             'path': 'ldapgroup',
                                                                             'path_param_names': '',
                                                                             'path_params': []},
 "/networkservice_importAction_networkservice/import_{'Content-Type': 'application/x-zip'}_": {'Content-Type': {'Content-Type': 'application/x-zip'},
                                                                                               'class': '/networkservice',
                                                                                               'method_alias': 'importAction',
                                                                                               'name': 'importAction',
                                                                                               'path': 'networkservice/import',
                                                                                               'path_param_names': '',
                                                                                               'path_params': []},
 "/networkservice_importAction_networkservice/import_{'Content-Type': 'application/xml'}_": {'Content-Type': {'Content-Type': 'application/xml'},
                                                                                             'class': '/networkservice',
                                                                                             'method_alias': 'importActionXML',
                                                                                             'name': 'importAction',
                                                                                             'path': 'networkservice/import',
                                                                                             'path_param_names': '',
                                                                                             'path_params': []},
 "/networkservicetype_importAction_networkservicetype/import_{'Content-Type': 'application/x-zip'}_": {'Content-Type': {'Content-Type': 'application/x-zip'},
                                                                                                       'class': '/networkservicetype',
                                                                                                       'method_alias': 'importAction',
                                                                                                       'name': 'importAction',
                                                                                                       'path': 'networkservicetype/import',
                                                                                                       'path_param_names': '',
                                                                                                       'path_params': []},
 "/networkservicetype_importAction_networkservicetype/import_{'Content-Type': 'application/xml'}_": {'Content-Type': {'Content-Type': 'application/xml'},
                                                                                                     'class': '/networkservicetype',
                                                                                                     'method_alias': 'importActionXML',
                                                                                                     'name': 'importAction',
                                                                                                     'path': 'networkservicetype/import',
                                                                                                     'path_param_names': '',
                                                                                                     'path_params': []},
 '/onboard_getOnboardMeta_onboard/meta/{id}_{}_id': {'Content-Type': {},
                                                     'class': '/onboard',
                                                     'method_alias': 'getOnboardMetaById',
                                                     'name': 'getOnboardMeta',
                                                     'path': 'onboard/meta/{id}',
                                                     'path_param_names': 'id',
                                                     'path_params': [{'alias': 'meta_id',
                                                                      'defaultValue': None,
                                                                      'kind': 'xs:int',
                                                                      'name': 'id',
                                                                      'required': False}]},
 '/onboard_getOnboardMeta_onboard/meta_{}_': {'Content-Type': {},
                                              'class': '/onboard',
                                              'method_alias': 'getOnboardMeta',
                                              'name': 'getOnboardMeta',
                                              'path': 'onboard/meta',
                                              'path_param_names': '',
                                              'path_params': []},
 '/onboard_searchUnmanagedInstances_onboard/search/{cloudId}_{}_cloudId': {'Content-Type': {},
                                                                           'class': '/onboard',
                                                                           'method_alias': 'searchUnmanagedInstancesByCloud',
                                                                           'name': 'searchUnmanagedInstances',
                                                                           'path': 'onboard/search/{cloudId}',
                                                                           'path_param_names': 'cloudId',
                                                                           'path_params': [{'alias': 'search_cloudId',
                                                                                            'defaultValue': None,
                                                                                            'kind': 'xs:int',
                                                                                            'name': 'cloudId',
                                                                                            'required': False}]},
 '/onboard_searchUnmanagedInstances_onboard/search_{}_': {'Content-Type': {},
                                                          'class': '/onboard',
                                                          'method_alias': 'searchUnmanagedInstances',
                                                          'name': 'searchUnmanagedInstances',
                                                          'path': 'onboard/search',
                                                          'path_param_names': '',
                                                          'path_params': []},
 "/project_importAction_project/import_{'Content-Type': 'application/x-zip'}_": {'Content-Type': {'Content-Type': 'application/x-zip'},
                                                                                 'class': '/project',
                                                                                 'method_alias': 'importAction',
                                                                                 'name': 'importAction',
                                                                                 'path': 'project/import',
                                                                                 'path_param_names': '',
                                                                                 'path_params': []},
 "/project_importAction_project/import_{'Content-Type': 'application/xml'}_": {'Content-Type': {'Content-Type': 'application/xml'},
                                                                               'class': '/project',
                                                                               'method_alias': 'importActionXML',
                                                                               'name': 'importAction',
                                                                               'path': 'project/import',
                                                                               'path_param_names': '',
                                                                               'path_params': []},
 "/project_importIDAction_project/{id}/import_{'Content-Type': 'application/x-zip'}_id": {'Content-Type': {'Content-Type': 'application/x-zip'},
                                                                                          'class': '/project',
                                                                                          'method_alias': 'importIDAction',
                                                                                          'name': 'importIDAction',
                                                                                          'path': 'project/{id}/import',
                                                                                          'path_param_names': 'id',
                                                                                          'path_params': [{'alias': 'project_id',
                                                                                                           'defaultValue': None,
                                                                                                           'kind': 'xs:int',
                                                                                                           'name': 'id',
                                                                                                           'required': True}]},
 "/project_importIDAction_project/{id}/import_{'Content-Type': 'application/xml'}_id": {'Content-Type': {'Content-Type': 'application/xml'},
                                                                                        'class': '/project',
                                                                                        'method_alias': 'importIDActionXML',
                                                                                        'name': 'importIDActionXML',
                                                                                        'path': 'project/{id}/import',
                                                                                        'path_param_names': 'id',
                                                                                        'path_params': [{'alias': 'project_id',
                                                                                                         'defaultValue': None,
                                                                                                         'kind': 'xs:int',
                                                                                                         'name': 'id',
                                                                                                         'required': True}]},
 "/projectrole_importAction_projectrole/import_{'Content-Type': 'application/x-zip'}_": {'Content-Type': {'Content-Type': 'application/x-zip'},
                                                                                         'class': '/projectrole',
                                                                                         'method_alias': 'importAction',
                                                                                         'name': 'importAction',
                                                                                         'path': 'projectrole/import',
                                                                                         'path_param_names': '',
                                                                                         'path_params': []},
 "/projectrole_importAction_projectrole/import_{'Content-Type': 'application/xml'}_": {'Content-Type': {'Content-Type': 'application/xml'},
                                                                                       'class': '/projectrole',
                                                                                       'method_alias': 'importActionXML',
                                                                                       'name': 'importAction',
                                                                                       'path': 'projectrole/import',
                                                                                       'path_param_names': '',
                                                                                       'path_params': []},
 "/propertygroup_importAction_propertygroup/import_{'Content-Type': 'application/x-zip'}_": {'Content-Type': {'Content-Type': 'application/x-zip'},
                                                                                             'class': '/propertygroup',
                                                                                             'method_alias': 'importAction',
                                                                                             'name': 'importAction',
                                                                                             'path': 'propertygroup/import',
                                                                                             'path_param_names': '',
                                                                                             'path_params': []},
 "/propertygroup_importAction_propertygroup/import_{'Content-Type': 'application/xml'}_": {'Content-Type': {'Content-Type': 'application/xml'},
                                                                                           'class': '/propertygroup',
                                                                                           'method_alias': 'importActionXML',
                                                                                           'name': 'importAction',
                                                                                           'path': 'propertygroup/import',
                                                                                           'path_param_names': '',
                                                                                           'path_params': []},
 "/propertytype_importAction_propertytype/import_{'Content-Type': 'application/x-zip'}_": {'Content-Type': {'Content-Type': 'application/x-zip'},
                                                                                           'class': '/propertytype',
                                                                                           'method_alias': 'importAction',
                                                                                           'name': 'importAction',
                                                                                           'path': 'propertytype/import',
                                                                                           'path_param_names': '',
                                                                                           'path_params': []},
 "/propertytype_importAction_propertytype/{id}/import_{'Content-Type': 'application/xml'}_": {'Content-Type': {'Content-Type': 'application/xml'},
                                                                                              'class': '/propertytype',
                                                                                              'method_alias': 'importActionXML',
                                                                                              'name': 'importAction',
                                                                                              'path': 'propertytype/{id}/import',
                                                                                              'path_param_names': '',
                                                                                              'path_params': []},
 '/repository_getRepositories_repository/{usage: (templates)|(instances)|(storage)|(attachments)|(backups)}_{}_usage': {'Content-Type': {},
                                                                                                                        'class': '/repository',
                                                                                                                        'method_alias': 'getRepositoriesByUsage',
                                                                                                                        'name': 'getRepositories',
                                                                                                                        'path': 'repository/{usage: (templates)|(instances)|(storage)|(attachments)|(backups)}',
                                                                                                                        'path_param_names': 'usage',
                                                                                                                        'path_params': [{'alias': 'repository_usage',
                                                                                                                                         'defaultValue': None,
                                                                                                                                         'kind': 'xs:string',
                                                                                                                                         'name': 'usage',
                                                                                                                                         'required': False}]},
 '/repository_getRepositories_repository_{}_': {'Content-Type': {},
                                                'class': '/repository',
                                                'method_alias': 'getRepositories',
                                                'name': 'getRepositories',
                                                'path': 'repository',
                                                'path_param_names': '',
                                                'path_params': []},
 "/repository_importAction_repository/import_{'Content-Type': 'application/x-zip'}_": {'Content-Type': {'Content-Type': 'application/x-zip'},
                                                                                       'class': '/repository',
                                                                                       'method_alias': 'importAction',
                                                                                       'name': 'importAction',
                                                                                       'path': 'repository/import',
                                                                                       'path_param_names': '',
                                                                                       'path_params': []},
 "/repository_importAction_repository/import_{'Content-Type': 'application/xml'}_": {'Content-Type': {'Content-Type': 'application/xml'},
                                                                                     'class': '/repository',
                                                                                     'method_alias': 'importActionXML',
                                                                                     'name': 'importAction',
                                                                                     'path': 'repository/import',
                                                                                     'path_param_names': '',
                                                                                     'path_params': []},
 "/setup_importAction_setup/import_{'Content-Type': 'application/x-zip'}_": {'Content-Type': {'Content-Type': 'application/x-zip'},
                                                                             'class': '/setup',
                                                                             'method_alias': 'importAction',
                                                                             'name': 'importAction',
                                                                             'path': 'setup/import',
                                                                             'path_param_names': '',
                                                                             'path_params': []},
 "/setup_importAction_setup/import_{'Content-Type': 'application/xml'}_": {'Content-Type': {'Content-Type': 'application/xml'},
                                                                           'class': '/setup',
                                                                           'method_alias': 'importActionXML',
                                                                           'name': 'importAction',
                                                                           'path': 'setup/import',
                                                                           'path_param_names': '',
                                                                           'path_params': []},
 "/setup_setProperty_setup/{id}/property/{propid}_{'Content-Type': 'application/x-www-form-urlencoded'}_id_propid": {'Content-Type': {'Content-Type': 'application/x-www-form-urlencoded'},
                                                                                                                     'class': '/setup',
                                                                                                                     'method_alias': 'setProperty',
                                                                                                                     'name': 'setProperty',
                                                                                                                     'path': 'setup/{id}/property/{propid}',
                                                                                                                     'path_param_names': 'id_propid',
                                                                                                                     'path_params': [{'alias': 'setup_id',
                                                                                                                                      'defaultValue': None,
                                                                                                                                      'kind': 'xs:int',
                                                                                                                                      'name': 'id',
                                                                                                                                      'required': True},
                                                                                                                                     {'alias': 'property_propid',
                                                                                                                                      'defaultValue': None,
                                                                                                                                      'kind': 'xs:int',
                                                                                                                                      'name': 'propid',
                                                                                                                                      'required': False}]},
 "/setup_setProperty_setup/{id}/property/{propid}_{'Content-Type': 'application/xml'}_id_propid": {'Content-Type': {'Content-Type': 'application/xml'},
                                                                                                   'class': '/setup',
                                                                                                   'method_alias': 'setPropertyXML',
                                                                                                   'name': 'setProperty',
                                                                                                   'path': 'setup/{id}/property/{propid}',
                                                                                                   'path_param_names': 'id_propid',
                                                                                                   'path_params': [{'alias': 'setup_id',
                                                                                                                    'defaultValue': None,
                                                                                                                    'kind': 'xs:int',
                                                                                                                    'name': 'id',
                                                                                                                    'required': True},
                                                                                                                   {'alias': 'property_propid',
                                                                                                                    'defaultValue': None,
                                                                                                                    'kind': 'xs:int',
                                                                                                                    'name': 'propid',
                                                                                                                    'required': False}]},
 '/storeedition_order_storeedition/{id}/order/{locationId}_{}_id_locationId': {'Content-Type': {},
                                                                               'class': '/storeedition',
                                                                               'method_alias': 'orderByLocation',
                                                                               'name': 'order',
                                                                               'path': 'storeedition/{id}/order/{locationId}',
                                                                               'path_param_names': 'id_locationId',
                                                                               'path_params': [{'alias': 'storeedition_id',
                                                                                                'defaultValue': None,
                                                                                                'kind': 'xs:int',
                                                                                                'name': 'id',
                                                                                                'required': True},
                                                                                               {'alias': 'order_locationId',
                                                                                                'defaultValue': None,
                                                                                                'kind': 'xs:int',
                                                                                                'name': 'locationId',
                                                                                                'required': False}]},
 "/storeedition_order_storeedition/{id}/order_{'Content-Type': 'application/xml'}_id": {'Content-Type': {'Content-Type': 'application/xml'},
                                                                                        'class': '/storeedition',
                                                                                        'method_alias': 'order',
                                                                                        'name': 'order',
                                                                                        'path': 'storeedition/{id}/order',
                                                                                        'path_param_names': 'id',
                                                                                        'path_params': [{'alias': 'storeedition_id',
                                                                                                         'defaultValue': None,
                                                                                                         'kind': 'xs:int',
                                                                                                         'name': 'id',
                                                                                                         'required': True}]},
 '/template_updateAlias_template/{id}/alias/{alias_id: [0-9]+}_{}_id_alias_id': {'Content-Type': {},
                                                                                 'class': '/template',
                                                                                 'method_alias': 'updateAlias',
                                                                                 'name': 'updateAlias',
                                                                                 'path': 'template/{id}/alias/{alias_id: [0-9]+}',
                                                                                 'path_param_names': 'id_alias_id',
                                                                                 'path_params': [{'alias': 'template_id',
                                                                                                  'defaultValue': None,
                                                                                                  'kind': 'xs:int',
                                                                                                  'name': 'id',
                                                                                                  'required': True},
                                                                                                 {'alias': 'alias_id',
                                                                                                  'defaultValue': None,
                                                                                                  'kind': 'xs:int',
                                                                                                  'name': 'alias_id',
                                                                                                  'required': False}]},
 '/template_updateAlias_template/{id}/alias/{name: [a-zA-Z0-9_\\-]+}_{}_id_name': {'Content-Type': {},
                                                                                   'class': '/template',
                                                                                   'method_alias': 'updateAliasByName',
                                                                                   'name': 'updateAlias',
                                                                                   'path': 'template/{id}/alias/{name: [a-zA-Z0-9_\\-]+}',
                                                                                   'path_param_names': 'id_name',
                                                                                   'path_params': [{'alias': 'template_id',
                                                                                                    'defaultValue': None,
                                                                                                    'kind': 'xs:int',
                                                                                                    'name': 'id',
                                                                                                    'required': True},
                                                                                                   {'alias': 'alias_name',
                                                                                                    'defaultValue': None,
                                                                                                    'kind': 'xs:string',
                                                                                                    'name': 'name',
                                                                                                    'required': False}]},
 "/topology_importIDAction_topology/{id}/import_{'Content-Type': 'application/x-zip'}_id": {'Content-Type': {'Content-Type': 'application/x-zip'},
                                                                                            'class': '/topology',
                                                                                            'method_alias': 'importIDAction',
                                                                                            'name': 'importIDAction',
                                                                                            'path': 'topology/{id}/import',
                                                                                            'path_param_names': 'id',
                                                                                            'path_params': [{'alias': 'topology_id',
                                                                                                             'defaultValue': None,
                                                                                                             'kind': 'xs:int',
                                                                                                             'name': 'id',
                                                                                                             'required': True}]},
 "/topology_importIDAction_topology/{id}/import_{'Content-Type': 'application/xml'}_id": {'Content-Type': {'Content-Type': 'application/xml'},
                                                                                          'class': '/topology',
                                                                                          'method_alias': 'importIDActionXML',
                                                                                          'name': 'importIDAction',
                                                                                          'path': 'topology/{id}/import',
                                                                                          'path_param_names': 'id',
                                                                                          'path_params': [{'alias': 'topology_id',
                                                                                                           'defaultValue': None,
                                                                                                           'kind': 'xs:int',
                                                                                                           'name': 'id',
                                                                                                           'required': True}]},
 "/user_importAction_user/import_{'Content-Type': 'application/x-zip'}_": {'Content-Type': {'Content-Type': 'application/x-zip'},
                                                                           'class': '/user',
                                                                           'method_alias': 'importAction',
                                                                           'name': 'importAction',
                                                                           'path': 'user/import',
                                                                           'path_param_names': '',
                                                                           'path_params': []},
 "/user_importAction_user/import_{'Content-Type': 'application/xml'}_": {'Content-Type': {'Content-Type': 'application/xml'},
                                                                         'class': '/user',
                                                                         'method_alias': 'importActionXML',
                                                                         'name': 'importAction',
                                                                         'path': 'user/import',
                                                                         'path_param_names': '',
                                                                         'path_params': []},
 "/usergroup_importAction_usergroup/import_{'Content-Type': 'application/x-zip'}_": {'Content-Type': {'Content-Type': 'application/x-zip'},
                                                                                     'class': '/usergroup',
                                                                                     'method_alias': 'importAction',
                                                                                     'name': 'importAction',
                                                                                     'path': 'usergroup/import',
                                                                                     'path_param_names': '',
                                                                                     'path_params': []},
 "/usergroup_importAction_usergroup/import_{'Content-Type': 'application/xml'}_": {'Content-Type': {'Content-Type': 'application/xml'},
                                                                                   'class': '/usergroup',
                                                                                   'method_alias': 'importActionXML',
                                                                                   'name': 'importAction',
                                                                                   'path': 'usergroup/import',
                                                                                   'path_param_names': '',
                                                                                   'path_params': []}}